dist: trusty
language: python

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36

services:
  - postgresql

before_script:
  - psql -c "CREATE USER admin WITH PASSWORD 'password';" -U postgres
  - psql -c "CREATE DATABASE test OWNER admin;" -U postgres

install:
  - pip install tox

script:
  - tox
