dist: trusty
language: python

matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE test;" -U postgres
  - psql -c "CREATE USER admin WITH PASSWORD 'password';" -U postgres

install:
  - ./.travis/install

script:
  - ./.travis/run tox
