"""2018-09-19_11:47

Revision ID: b66ca483b3ef
Revises:
Create Date: 2018-09-19 11:47:33.766242

"""

# revision identifiers, used by Alembic.
revision = 'b66ca483b3ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
